import Head from "next/head";
import React from "react";
import { Header } from "../Header";

interface Props {
  pageTitle: string;
  children?: React.ReactNode;
}

export const Layout: React.FC<Props> = ({ pageTitle, children }) => {
  return (
    <div>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mb-10">
        <Header />
      </div>

      <div className="container mx-auto">{children}</div>
    </div>
  );
};
